### ISSUE TITLE
Hi，a question about filefolder "Robot_Description_Files"

### ISSUE THREAD

**Issue by Muziyun123456** [TUM-ICS/BIRDy#4]
It's said folder " Robot_Description_Files" is in "Benchmark/Robot_Data_Generation/Dynamic_Model_Generation/Robot_Description_Files". but in the file that I downloaded,this folder is in "BIRDy-main\Utils\SymbolicModelData\RobotDescriptionFiles". So is it wrong in Readme.md?

**Comment by quentin-leboutet** [comment]
Good catch, thanks. I corrected the readme file.
