### ISSUE TITLE
Can I get the full parameters of robot using bijective mapping m from base parameters.

### ISSUE THREAD

**Issue by MuziYT** [TUM-ICS/BIRDy#5]
I can get base parameters by PC_DIDIM method, when I calculate the full parameters of robot using bijective mapping  from base parameters, but it also has ![image](https://github.com/TUM-ICS/BIRDy/assets/115478608/634bb1ac-a1dc-429f-aa86-2890f74d68ab), so is there some method to solve this problem? thank you!

**Comment by quentin-leboutet** [comment]
Hi MuziYT, 

you might be interested in equation (11), page 10 of https://mediatum.ub.tum.de/doc/1638193/document.pdf 
Please let me know if this answers your question.

**Comment by MuziYT** [comment]
Hi, Quentin Leboutet
Thanks you a lot, I know that full dynamic parameters can be obtained through SDP and a bijective mapping(equation 11), but I would like to ask if your program can directly output full dynamic parameters. If not, I will try to modify it. Thanks you agian.

**Comment by quentin-leboutet** [comment]
So far the code only outputs estimates of the base parameter vector Beta. However, all the quantities you need to recompute the standard parameter vector from this estimate should be available. In fact, the standard parameters are used to build the LMI of PC identification routines. Check the [buildLMI()](https://github.com/TUM-ICS/BIRDy/blob/main/Benchmark/Robot_Identification_Algorithms/Utils/buildLMI.m) function: this might be what you are looking for (line 18).

If you want to know where these different quantities are computed, check the [computeIdentificationModel()](https://github.com/TUM-ICS/BIRDy/blob/971242479fef3e0aaa4889264b32a4e5a4065786/Benchmark/Robot_Data_Generation/Dynamic_Model_Generation/computeSymbolicDynamics.m#LL201C43-L201C69 ) routine. There, in the [baseParametersNumericalSimplification()](https://github.com/TUM-ICS/BIRDy/blob/971242479fef3e0aaa4889264b32a4e5a4065786/Benchmark/Robot_Data_Generation/Dynamic_Model_Generation/Utils/computeIdentificationModel.m#LL125C53-L125C91) function you can see that all the quantities of equation 11 involved in the mapping, in particular the permutation matrix P (denoted as Perm), the product of R terms (denoted as K_d) and the vector of unidentifiable parameters (denoted as X_d) are exported as Matlab functions named _Regressor_Perm_<robot_name>.mat_, _Regressor_K_d_<robot_name>.mat_ and _Regressor_Xhi_d_<robot_name>.m_ respectively.

**Comment by MuziYT** [comment]
Hi, Quentin Leboutet
Thank you a lot,I will carefully read the code and find the way to obtain the standard parameter vector.
