### ISSUE TITLE
Excitation trajectory generation with constraints

### ISSUE THREAD

**Issue by jimi1970** [TUM-ICS/BIRDy#6]
Dear Quentin Leboutet, first of all I would like to thank you and your colleagues for creating this great benchmark. I came across your paper and benchmark only recently, but during a cursory testing of it I came across the problem of including physical constraints (limits on positions, velocities, accelerations and moments) in the generation of the excitation trajectory. I tried using your bechmark to create a simple robot model, but the generated excitation trajectory did not respect the physical constraints I specified in the robot model. I assume that by default the excitation trajectory does not respect the limits, but unfortunately I could not find a ''command'' to change it to include the physical limits. Could I please ask how to set the benchmark to respect physical limits for excitation trajectory generation?
Thank you in advance for the answer.

**Comment by quentin-leboutet** [comment]
Hi, this came from a bug in generateExcitationTrajectory.m: the value of MaxFunctionEvaluations was wrong. I corrected it.
