### ISSUE TITLE
Friction models

### ISSUE THREAD

**Issue by MarinicVojtech** [TUM-ICS/BIRDy#7]
Dear Quentin Leboutet, 

i am using your benchmark rigth now in my masters work and i would like to ask about friction models. I did identification on my robot with using ViscousCoulomb friction model and it was all fine. But now, i would like to use other friction models and your benchmark has some problem with it. 

First i set these parameters in description file to "no" like this:
robot.frictionDatagenModel = 'no'
robot.frictionIdentModel = 'no'; 

and then i start the benchmark. It pops error in file "pseudoInertiaMatrix_Xhi" that index i out of array elements. In this function i tried more things, like:
- comment Fci = Xhi_i(13) or set it to zero
- make the final P matrix smaller (so the function is not using this parameter)

and nothing works. Specifically, after this changes, benchmark is not showing error and it all looks good. But he writtes Experiment data ready and then nothing. He always breaks and nothing happen. I think that he is stuck in function called "!generateInitParamExt.m" between row number 108 and 116. 

I tried to figure it out many times, but i always failed, so i would like to ask you for help. I hope that my description is understandable and we will figure it out.

Thanks in advance.
Marinič Vojtěch

**Comment by quentin-leboutet** [comment]
Hi, 
the lines 106-116 of [generateInitParamEst](https://github.com/TUM-ICS/BIRDy/blob/ff47a050e6e421aa12e0d28105c61b884e56c544/Benchmark/Robot_Identification_Algorithms/Utils/generateInitParamEst.m#L106) are checking the physical consistency of the initial parameter vector by building the so called [pseudo-inertia matrix](https://ieeexplore.ieee.org/ielaam/7083369/8013191/7987066-aam.pdf) associated with your standard parameter vector an checking its positive-definiteness through a Cholesky decomposition. In its current version, `pseudoInertiaMatrix_Xhi` is indeed not robust to changes in the dimensionality of the standard parameter vector `Xhi_i` and basically assumes a viscous-coulomb friction model. To solve this issue, you may want to make this function a bit more flexible and try something like this: 
```
function [P_i] = pseudoInertiaMatrix_Xhi(Xhi_i)

Li = inertiaMatrix(Xhi_i(1), Xhi_i(2), Xhi_i(3), Xhi_i(4), Xhi_i(5), Xhi_i(6));
li = Xhi_i(7:9);
Mi = Xhi_i(10);

additional_parameters = diag(Xhi_i(11:end));
offset = length(Xhi_i(11:end));
    
P_i = [[(trace(Li)/2)*eye(3)-Li, li; li', Mi], zeros(4,offset);...
       zeros(offset,4), additional_parameters];

end
```

As I no longer have access to Matlab, I unfortunately cannot test these changes myself. Could you tell me if this solves your issue or if other issues emerge as a result of this change?

**Comment by MarinicVojtech** [comment]
Hello,

first of all, thanks for your quick answer. Unfortunately, I changed old code in function _pseudoInertiaMatrix_Xhi_ for the new one you sent yesterday, but the problem is still there. No error, no warning, but program will breaks (i think in the same place as before ("generateInitParamExt.m" between row number 108 and 116.)).

**Comment by quentin-leboutet** [comment]
You may then try to - temporarily - comment out lines 106-116 of [generateInitParamEst](https://github.com/TUM-ICS/BIRDy/blob/ff47a050e6e421aa12e0d28105c61b884e56c544/Benchmark/Robot_Identification_Algorithms/Utils/generateInitParamEst.m#L106)

**Comment by MarinicVojtech** [comment]
Well, that works. Thanks
