### ISSUE TITLE
robots regressor computation functions 

### ISSUE THREAD

**Issue by wissem01chiha** [TUM-ICS/BIRDy#9]
Dear Dr. Leboutet ;

Thank you very much for the research benchmark,  When i reviewed  your  code , i cannot find the robots regressors functions definition
such as : `Regressor_Y_SCARA, Regressor_Y_toyRobot,...  `  in  [observartionMatrix.m](https://github.com/TUM-ICS/BIRDy/blob/ff47a050e6e421aa12e0d28105c61b884e56c544/Benchmark/Robot_Identification_Algorithms/Utils/observationMatrix.m#L16), i am not sure that this function is a built in MATLAB function because i cannot find it in the official documentations. In addition if this are custom specific functions for SCARA , UR5  robots models,  we shall write our regressor implementation in order to add a new robot model !. 
I am looking for a general implementation in MATLAB or C++ for robot regressors computations , for my research project , is there a solution ?

**Comment by quentin-leboutet** [comment]
Hello, 

these functions are normally generated with the [identification model](https://github.com/TUM-ICS/BIRDy#how-to-regenerate-the-indentification-model-of-a-robot) of your robot. This should normally be done [automatically](https://github.com/TUM-ICS/BIRDy/blob/ff47a050e6e421aa12e0d28105c61b884e56c544/Utils/initBenchmark.m#L192). More specifically, the `Regressor_Y_...` functions are generated in the [computeSymbolicDynamics](https://github.com/TUM-ICS/BIRDy/blob/ff47a050e6e421aa12e0d28105c61b884e56c544/Benchmark/Robot_Data_Generation/Dynamic_Model_Generation/computeSymbolicDynamics.m#L201) function and [optimized ](https://github.com/TUM-ICS/BIRDy/blob/ff47a050e6e421aa12e0d28105c61b884e56c544/Benchmark/Robot_Data_Generation/Dynamic_Model_Generation/computeSymbolicDynamics.m#L237) using a [matlabFunction](https://www.mathworks.com/help/symbolic/sym.matlabfunction.html). The detail of the regressor computation can be found in the [computeIdentificationModel](https://github.com/TUM-ICS/BIRDy/blob/main/Benchmark/Robot_Data_Generation/Dynamic_Model_Generation/Utils/computeIdentificationModel.m) routine.
